#!/bin/bash

ENV_DIR=env
OUT_DIR=../../build/c-protobufs
MSG_DIR=../../messages

# Setup virtual environment
if [ ! -d "$ENV_DIR" ]; then
    # Install nanopb requirements
    python3 -m venv $ENV_DIR
    source env/bin/activate
    pip3 install -r nanopb/requirements.txt
else
    source env/bin/activate
fi

# Generate Protobuf payloads for C
if [ ! -d "$OUT_DIR" ]; then
    mkdir -p $OUT_DIR
fi 
python3 nanopb/generator/nanopb_generator.py -I $MSG_DIR $MSG_DIR/*.proto -D $OUT_DIR

# Exit virtual environment
deactivate