#!/bin/bash

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
ENV_DIR=$SCRIPT_DIR/env
OUT_DIR=$SCRIPT_DIR/../../build/CAVeTalk_c_protos
MSG_DIR=$SCRIPT_DIR/../../messages
NANOPB_DIR=$SCRIPT_DIR/nanopb

# Setup virtual environment
if [ ! -d "$ENV_DIR" ]; then
    # Install nanopb requirements
    python3 -m venv $ENV_DIR
    source $ENV_DIR/bin/activate
    pip3 install -r $NANOPB_DIR/requirements.txt
else
    source $ENV_DIR/bin/activate
fi

# Generate Protobuf payloads for C
if [ ! -d "$OUT_DIR" ]; then
    mkdir -p $OUT_DIR
fi 
python3 $NANOPB_DIR/generator/nanopb_generator.py -I $MSG_DIR $MSG_DIR/*.proto -D $OUT_DIR

# Exit virtual environment
deactivate